name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, almalinux/8]
        python-version: [3.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install pyinstaller
          # Additional dependencies if needed

      - name: Build executable
        run: |
          pyinstaller triny_cli.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: dist
